[package]
edition = "2021"
name = "ERPAnalytics"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rand = "0.8.5"
serde = "1.0.137"

[dependencies.rocket]
features = ["json"]
version = "0.5.0-rc.2"
